package com.descritas.cocktailapp.model

import com.descritas.cocktailapp.dto.Card

data class CardModel (
    val cards: List<Card> = emptyList(),
        /*Card(
        0,
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        false),*/
    val loading: Boolean = false,
    val refreshing: Boolean = false,
    val error: Boolean = false,)
